make hooks better; fix repeated install problem; version --> 0.7.1.8-18ad5e23dc

diff --git a/nitro-hook b/nitro-hook
--- a/nitro-hook
+++ b/nitro-hook
@@ -1,45 +1,54 @@
 #!/bin/sh -e
 
 nitro_live() {
-  if [ ! -L /run/nitro/sv ]; then
-    echo >&2 "  Skipped: Current root is not booted."
-    exit 0
-  fi
+	local fn="/run/nitro/nitro.sock"
+	if [ ! -S "$fn" ] || [ "$(lsof -Fp "$fn")" != "p1" ]; then
+		echo >&2 "  Skipped: Current root is not booted."
+		exit 0
+	fi
 }
 
 svc_help(){
-    echo "	==> Start/stop/restart a service:"
-    echo "	nsm <start/stop/restart> <service>"
+	echo "  ==> Start/stop/restart a service:"
+	echo "  nsm <start/stop/restart> <service>"
 }
 
 svc_add_help(){
-    echo "	==> Add a service:"
-    echo "	nsm enable <service>"
-    svc_help
+	echo "  ==> Add a service:"
+	echo "  nsm enable <service>"
+	svc_help
 }
 
 svc_del_help(){
-    echo "	==> Remove a service:"
-    echo "	nsm disable <service>"
-    svc_help
+	echo "  ==> Remove a service:"
+	echo "  nsm disable <service>"
+	svc_help
 }
 
 each_conf() {
-  while read -r f; do
-    "$@" "/$f"
-  done
+	while read -r f; do
+		"$@" "/$f"
+	done
+}
+
+rename_1_exe(){
+	local exe="$(readlink /proc/1/exe 2>/dev/null || true)"
+	if [ -n "$exe" -a -x "$exe" ]; then
+		mv "$exe" "/usr/bin/old-proc-1-exe"
+	fi
 }
 
 op="$1"; shift
 
 case $op in
-  sysctl)   nitro_live; each_conf /usr/bin/sysctl -q -p ;;
-  binfmt)   nitro_live; each_conf /usr/lib/rc/sv.d/binfmt once ;;
-    # For use by other packages
-  reload)   nitro_live; /usr/bin/sv "$@" reload ;;
-  add)      svc_add_help ;;
-  del)      svc_del_help ;;
-  *) echo >&2 "  Invalid operation '$op'"; exit 1 ;;
+	(sysctl) nitro_live; each_conf /usr/bin/sysctl -q -p ;;
+	(binfmt) nitro_live; each_conf /usr/lib/rc/sv.d/binfmt once ;;
+	(init-nitro-pre) rename_1_exe;;
+	(init-nitro-post) echo "  init-nitro-post is not yet implemented" >&2; exit 0;;
+	(reload) nitro_live; /usr/bin/sv "$@" reload ;;
+	(add) svc_add_help ;;
+	(del) svc_del_help ;;
+	(*) echo >&2 "  Invalid operation '$op'"; exit 1 ;;
 esac
 
 exit 0
